/**
 * RealtimeService - WebSocket/SSE connection management
 * Generated by Phase 2 migration script
 * 
 * Handles real-time communication with backend using WEBSOCKET
 */

import { Injectable, inject } from '@angular/core';
import { Observable, Subject, BehaviorSubject, fromEvent, timer } from 'rxjs';
import { 
  map, 
  filter, 
  retry, 
  retryWhen, 
  delay, 
  tap, 
  catchError, 
  takeUntil 
} from 'rxjs/operators';
import { AuthService } from '../../domains/authentication';

export enum ConnectionState {
  CONNECTING = 'connecting',
  CONNECTED = 'connected',
  DISCONNECTED = 'disconnected',
  RECONNECTING = 'reconnecting',
  ERROR = 'error'
}

export interface RealtimeEvent<T = any> {
  type: string;
  data: T;
  timestamp: number;
}

export interface RealtimeConfig {
  url: string;
  reconnectInterval?: number;
  reconnectAttempts?: number;
  heartbeatInterval?: number;
}

@Injectable({
  providedIn: 'root'
})
export class RealtimeService {
  private authService = inject(AuthService);
  
  private connection: WebSocket | null = null;
  private config: RealtimeConfig | null = null;
  
  // Subjects for state management
  private connectionState$ = new BehaviorSubject<ConnectionState>(ConnectionState.DISCONNECTED);
  private events$ = new Subject<RealtimeEvent>();
  private destroy$ = new Subject<void>();
  
  // Reconnection logic
  private reconnectAttempts = 0;
  private reconnectTimer: any = null;
  
  /**
   * Observable of connection state
   */
  getConnectionState(): Observable<ConnectionState> {
    return this.connectionState$.asObservable();
  }
  
  /**
   * Observable of all real-time events
   */
  getEvents(): Observable<RealtimeEvent> {
    return this.events$.asObservable();
  }
  
  /**
   * Observable of specific event type
   */
  on<T = any>(eventType: string): Observable<T> {
    return this.events$.pipe(
      filter(event => event.type === eventType),
      map(event => event.data as T)
    );
  }
  
  /**
   * Connect to real-time server
   */
  connect(config: RealtimeConfig): void {
    if (this.connection) {
      console.warn('Already connected to real-time server');
      return;
    }
    
    this.config = {
      reconnectInterval: 3000,
      reconnectAttempts: 10,
      heartbeatInterval: 30000,
      ...config
    };
    
    this.connectionState$.next(ConnectionState.CONNECTING);
    this.establishConnection();
  }
  
  /**
   * Disconnect from real-time server
   */
  disconnect(): void {
    this.destroy$.next();
    this.clearReconnectTimer();
    
    if (this.connection) {
      this.connection.close();
      this.connection = null;
    }
    
    this.connectionState$.next(ConnectionState.DISCONNECTED);
  }
  
  /**
   * Send event to server (WebSocket only)
   */
  send<T = any>(eventType: string, data: T): void {
    if (!this.connection || this.connection.readyState !== WebSocket.OPEN) {
      console.error('Cannot send event: not connected');
      return;
    }
    
    const event: RealtimeEvent<T> = {
      type: eventType,
      data,
      timestamp: Date.now()
    };
    
    this.connection.send(JSON.stringify(event));
  }
  
  /**
   * Private: Establish connection
   */
  private establishConnection(): void {
    if (!this.config) return;
    
    try {
      const token = this.authService.getAccessToken();
      const url = `${this.config.url}?token=${token}`;
      
      this.connection = new WebSocket(url);
      
      this.connection.onopen = () => {
        console.log('WebSocket connected');
        this.connectionState$.next(ConnectionState.CONNECTED);
        this.resetReconnectAttempts();
        this.startHeartbeat();
      };
      
      this.connection.onmessage = (event) => {
        try {
          const realtimeEvent: RealtimeEvent = JSON.parse(event.data);
          this.events$.next(realtimeEvent);
        } catch (error) {
          console.error('Failed to parse WebSocket message:', error);
        }
      };
      
      this.connection.onerror = (error) => {
        console.error('WebSocket error:', error);
        this.handleConnectionError();
      };
      
      this.connection.onclose = () => {
        console.log('WebSocket closed');
        this.connection = null;
        
        if (this.connectionState$.value !== ConnectionState.DISCONNECTED) {
          this.handleConnectionError();
        }
      };
      
    } catch (error) {
      console.error('Failed to establish connection:', error);
      this.handleConnectionError();
    }
  }
  
  /**
   * Check if connected
   */
  private isConnected(): boolean {
    return this.connection?.readyState === WebSocket.OPEN;
  }
  
  /**
   * Handle connection error and attempt reconnect
   */
  private handleConnectionError(): void {
    this.connectionState$.next(ConnectionState.ERROR);
    
    if (!this.config) return;
    
    if (this.reconnectAttempts < (this.config.reconnectAttempts || 10)) {
      this.reconnectAttempts++;
      this.connectionState$.next(ConnectionState.RECONNECTING);
      
      console.log(`Reconnecting... (attempt ${this.reconnectAttempts})`);
      
      this.reconnectTimer = setTimeout(() => {
        this.establishConnection();
      }, this.config.reconnectInterval || 3000);
    } else {
      console.error('Max reconnection attempts reached');
      this.connectionState$.next(ConnectionState.DISCONNECTED);
    }
  }
  
  /**
   * Clear reconnection timer
   */
  private clearReconnectTimer(): void {
    if (this.reconnectTimer) {
      clearTimeout(this.reconnectTimer);
      this.reconnectTimer = null;
    }
  }
  
  /**
   * Reset reconnection counter
   */
  private resetReconnectAttempts(): void {
    this.reconnectAttempts = 0;
    this.clearReconnectTimer();
  }
  
  /**
   * Start heartbeat (keep-alive)
   */
  private startHeartbeat(): void {
    if (!this.config?.heartbeatInterval) return;
    
    timer(0, this.config.heartbeatInterval)
      .pipe(takeUntil(this.destroy$))
      .subscribe(() => {
        this.send('heartbeat', { timestamp: Date.now() });
      });
  }
}
