/**
 * RealtimeService Tests
 * Generated by Phase 2 migration script
 */

import { TestBed } from '@angular/core/testing';
import { RealtimeService, ConnectionState } from './realtime.service';
import { AuthService } from '../../domains/authentication';

// Mock WebSocket
class MockWebSocket {
  readyState = WebSocket.CONNECTING;
  onopen: any;
  onmessage: any;
  onerror: any;
  onclose: any;
  
  constructor(public url: string) {
    setTimeout(() => {
      this.readyState = WebSocket.OPEN;
      if (this.onopen) this.onopen({});
    }, 0);
  }
  
  send(data: string): void {
    console.log('Mock send:', data);
  }
  
  close(): void {
    this.readyState = WebSocket.CLOSED;
    if (this.onclose) this.onclose({});
  }
  
  simulateMessage(data: any): void {
    if (this.onmessage) {
      this.onmessage({ data: JSON.stringify(data) });
    }
  }
}

describe('RealtimeService', () => {
  let service: RealtimeService;
  let mockAuthService: jasmine.SpyObj<AuthService>;
  let originalWebSocket: any;
  
  beforeEach(() => {
    mockAuthService = jasmine.createSpyObj('AuthService', ['getAccessToken']);
    mockAuthService.getAccessToken.and.returnValue('test-token');
    
    // Replace global WebSocket with mock
    originalWebSocket = (window as any).WebSocket;
    (window as any).WebSocket = MockWebSocket;
    
    TestBed.configureTestingModule({
      providers: [
        RealtimeService,
        { provide: AuthService, useValue: mockAuthService }
      ]
    });
    
    service = TestBed.inject(RealtimeService);
  });
  
  afterEach(() => {
    (window as any).WebSocket = originalWebSocket;
    service.disconnect();
  });
  
  it('should create', () => {
    expect(service).toBeTruthy();
  });
  
  it('should connect to WebSocket server', (done) => {
    service.getConnectionState().subscribe(state => {
      if (state === ConnectionState.CONNECTED) {
        expect(state).toBe(ConnectionState.CONNECTED);
        done();
      }
    });
    
    service.connect({ url: 'ws://localhost:3000' });
  });
  
  it('should receive real-time events', (done) => {
    service.on('test.event').subscribe(data => {
      expect(data).toEqual({ message: 'test' });
      done();
    });
    
    service.connect({ url: 'ws://localhost:3000' });
    
    // Simulate receiving a message
    setTimeout(() => {
      const ws = (service as any).connection as MockWebSocket;
      ws.simulateMessage({
        type: 'test.event',
        data: { message: 'test' },
        timestamp: Date.now()
      });
    }, 100);
  });
  
  it('should send events', (done) => {
    service.connect({ url: 'ws://localhost:3000' });
    
    setTimeout(() => {
      service.send('test.event', { message: 'hello' });
      done();
    }, 100);
  });
  
  it('should handle disconnection', (done) => {
    service.getConnectionState().subscribe(state => {
      if (state === ConnectionState.DISCONNECTED) {
        expect(state).toBe(ConnectionState.DISCONNECTED);
        done();
      }
    });
    
    service.connect({ url: 'ws://localhost:3000' });
    
    setTimeout(() => {
      service.disconnect();
    }, 100);
  });
  
  it('should attempt reconnection on error', (done) => {
    let stateChanges: ConnectionState[] = [];
    
    service.getConnectionState().subscribe(state => {
      stateChanges.push(state);
      
      if (state === ConnectionState.RECONNECTING) {
        expect(stateChanges).toContain(ConnectionState.ERROR);
        done();
      }
    });
    
    service.connect({ url: 'ws://localhost:3000', reconnectInterval: 100 });
    
    setTimeout(() => {
      const ws = (service as any).connection as MockWebSocket;
      if (ws.onerror) ws.onerror(new Error('Connection failed'));
    }, 100);
  });
});
